"""init

Revision ID: 26dd3465c090
Revises:
Create Date: 2017-02-12 11:01:38.873183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dd3465c090'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('content', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('image_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('update_info',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_info')
    op.drop_table('article')
    # ### end Alembic commands ###
