"""article view times

Revision ID: 4419ab81c7fc
Revises: 87a0db9c71e8
Create Date: 2017-02-13 15:45:32.317205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4419ab81c7fc'
down_revision = '87a0db9c71e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'views')
    # ### end Alembic commands ###
