"""update info

Revision ID: 87a0db9c71e8
Revises: a7317a4aab79
Create Date: 2017-02-12 15:18:12.120527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a0db9c71e8'
down_revision = 'a7317a4aab79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
