"""source

Revision ID: a7317a4aab79
Revises: 26dd3465c090
Create Date: 2017-02-12 14:47:05.830721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7317a4aab79'
down_revision = '26dd3465c090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('source', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'source')
    # ### end Alembic commands ###
